name: absenin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shared_preferences: 2.0.7
  geolocator: 8.0.1
  google_maps_flutter: ^2.1.8
  geocoding: ^2.0.4
  intl: 0.17.0


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/img/attendance.png"
  adaptive_icon_background: "#ffffff"
  # flutter pub run flutter_launcher_icons:main

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/img/
  
